### PR TITLE
Make 'method' param in JsonRoutes.add() case-insensitive

### PR DESCRIPTION
**Pull request by kahmali**
json-routes:
- Resolve Issue #31
- Update README
  - Add info on param being case-insensitive
  - Enforce 80 character line limit
  - Create a table of links for long URLs
  - Fix indentation in bullet-lists to improve readability of raw README
- Update change log

### CODE REVIEW

**Comment by aldeed** [comment]
LGTM, but why do we need to follow line limit for markdown? Seems like it should apply to code only.

**Comment by stubailo** [comment]
Yeah I usually use a visual editor for markdown so I don't really care
either way.

**Comment by kahmali** [comment]
The reason I always hard-wrapped my lines is because it makes the markdown more readable in places where soft-wrapping is available (since soft-wraps typically don't care about the indentation in the line they're wrapping). I use Jetbrains IDEs, and I recently found an option that actually _does_ take into account the indentation when soft-wrapping, so hard-wrapping the lines is definitely more of a hassle than what it's worth to me now. I can get rid of the char limit (and specify that in the contributing guidelines maybe). I thought I had a better reason, but after giving it a little thought I agree that markdown is never being viewed in a raw format unless it's in a visual editor nowadays. It might be some time before every editor has a cool option for respecting indentation when soft-wrapping, but if nobody else seems to care then I won't be the one crazy person making an issue of it.

**Comment by stubailo** [comment]
IMO having a code style for Markdown isn't really necessary, I would personally be OK with everyone just doing whatever they feel like.

**Comment by stubailo** [comment]
@kahmali is there a markdown auto-formatter somewhere that we could use to just have all of this stuff happen automatically? Then we can just run it in a commit hook or something and nobody has to worry about it.

**Comment by kahmali** [comment]
Great point @stubailo. Let me look into that. The more automation of these tasks, the better.

**Comment by kahmali** [comment]
_@stubailo: "IMO having a code style for Markdown isn't really necessary, I would personally be OK with everyone just doing whatever they feel like."_

I agree. As long as the output looks consistent throughout a document, the raw markdown shouldn't really be a concern. We can be worrying about more important things.

**Comment by stubailo** [comment]
In the meantime, going to merge this. We should figure out when to do the next release.

**Comment by aldeed** [comment]
:+1:

**Pull request merged**
